sudo: required

language: node_js
node_js:
  - node

services:
    - docker

before_install:
- docker pull postgres:9.6.5
- docker run -d -p 127.0.0.1:5432:5432 postgres:9.6.5

install: npm install

script: npm test
